"""Add credit card fields to User model

Revision ID: c8e1c74b35c0
Revises: 
Create Date: 2025-07-14 23:57:45.393129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e1c74b35c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card_balance', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('daily_credit_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_credit_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_credit_date')
        batch_op.drop_column('daily_credit_count')
        batch_op.drop_column('credit_card_balance')

    # ### end Alembic commands ###
